routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Products;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'checkUsertype'])->name('home');

Route::get('/admin/dashboard', function () {
    return view('admin.DashBoard.index');
})->middleware('auth')->name('admin.dashboard');
Route::get('/client/dashboard', function () {
    $categories=\App\Models\categories::all();
    $products=Products::paginate(10);
    return view('client.DashBoard.index',compact('products','categories'));
})->middleware('auth')->name('client.dashboard');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('Category',controller: \App\Http\Controllers\Category\CategoryController::class);
Route::get('/category', '\App\Http\Controllers\Category\CategoryController@index');

Route::get('/category/search', '\App\Http\Controllers\Category\CategoryController@search')->name('category.search');

Route::resource('Supplier',controller: \App\Http\Controllers\Supplier\SupplierController::class);
Route::resource('Product',controller: \App\Http\Controllers\Product\ProductController::class);
Route::get('/supplier/search', '\App\Http\Controllers\Supplier\SupplierController@search')->name('Supplier.search');
Route::get('/product/search', '\App\Http\Controllers\Product\ProductController@search')->name('Product.search');
Route::resource('Shipper',\App\Http\Controllers\Shipper\ShipperController::class);
Route::POST('/shipper/search', '\App\Http\Controllers\Shipper\ShipperController@search')->name('Shipper.search');
Route::resource('Customer',controller: \App\Http\Controllers\Customer\CustomerController::class);
Route::resource('Employee',controller: \App\Http\Controllers\Employee\EmployeeController::class);
Route::POST('/customer/search', '\App\Http\Controllers\Customer\CustomerController@search')->name('Customer.search');
Route::POST('/employee/search', '\App\Http\Controllers\Employee\EmployeeController@search')->name('Employee.search');
Route::resource('Order',\App\Http\Controllers\Order\OrderController::class);
Route::POST('/Order/search', '\App\Http\Controllers\Order\OrderController@search')->name('Order.search');
Route::POST('/Order/searchproduct', [\App\Http\Controllers\Order\OrderController::class, 'searchproduct'])->name('Order.searchproduct');
Route::POST('/Order/AddToCart', [\App\Http\Controllers\Order\OrderController::class, 'AddToCart'])->name('Order.AddToCart');
Route::GET('/Order/removeFromCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'removeFromCart'])->name('Order.removeFromCart');
Route::GET('/Order/RemoveCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveCart'])->name('Order.RemoveCart');
Route::POST('/Order/Init', [\App\Http\Controllers\Order\OrderController::class, 'Init'])->name('Order.Init');
Route::GET('/Order/RemoveDetail/{productId}/{orderid}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveDetail'])->name('Order.RemoveDetail');
Route::GET('/Order/Details/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Details'])->name('Order.Details');
Route::GET('/Order/Accept/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Accept'])->name('Order.Accept');
Route::GET('/Order/Shipping/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Shipping'])->name('Order.Shipping');
Route::POST('/Order/Shipped', [\App\Http\Controllers\Order\OrderController::class, 'Shipped'])->name('Order.Shipped');
Route::GET('/Order/Finished/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Finished'])->name('Order.Finished');
Route::GET('/Order/Cancel/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Cancel'])->name('Order.Cancel');
Route::GET('/Order/Reject/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Reject'])->name('Order.Reject');
Route::POST('/Client/Product/Search',[\App\Http\Controllers\client\Product\ProductController::class,'search'])->name('Client.Product.Search');
Route::GET('/Client/Product/Details/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'show'])->name('Client.Product.Details');
Route::GET('/Client/Product/AddToCart/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'AddToCart'])->name('Client.Product.AddToCart');

app/Models/Shipper.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shipper extends Model
{
    use HasFactory;

    protected $table='shippers';

    protected $fillable=[
        'ShipperName',
        'Phone'
    ];
}

app/Http/Controllers/Shipper/ShipperController.php
<?php

namespace App\Http\Controllers\Shipper;

use App\Http\Controllers\Controller;
use App\Models\Shipper;
use Illuminate\Http\Request;
use function PHPUnit\Framework\isEmpty;

class ShipperController extends Controller
{
    protected $Shipper;

    /**
     * @param $Shipper
     */
    public function __construct(Shipper $Shipper)
    {
        $this->Shipper = $Shipper;
    }


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $shipperList=$this->Shipper->paginate(10);
        return view('admin.Shipper.Index',['Shipper'=>$shipperList]);
    }

    public function search(Request  $request)
    {
        $perPage = 10;

        $searchValue = $request->input('searchValue'); // từ khóa tìm kiếm
        $request->session()->put('searchValue', $searchValue);
        $shipperList = $this->Shipper::where(function ($query) use ($searchValue) {
            $query->where('ShipperName', 'like', "%$searchValue%")
                ->orWhere('Phone', 'like', "%$searchValue%");
        })->paginate(10);

        return view('admin.Shipper.Search', ['Shipper' => $shipperList]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.Shipper.Create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'ShipperName' => 'required|max:50',
            'Phone' => 'required'
        ], [
            'ShipperName.required' => 'Tên người giao hàng không được bỏ trống',
            'ShipperName.max' => 'Tên người giao hàng không được vượt quá 50 kí tự',
            'Phone.required' => 'Số điện thoại không được bỏ trống'
        ]);

        // Xử lý lưu dữ liệu
        $dataRequest=$request->all();

        $Shipper=$this->Shipper->create($dataRequest);


        return redirect()->route('Shipper.index')->with('success', 'Thêm mới người giao hàng: '. $Shipper->ShipperName.' thành công');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $Shipper=$this->Shipper->findorfail($id);

        return view('admin.Shipper.Delete',compact('Shipper'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $Shipper=$this->Shipper->findorfail($id);
        return view('admin.Shipper.Edit',compact('Shipper'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'ShipperName' => 'required|max:50',
            'Phone' => 'required'
        ], [
            'ShipperName.required' => 'Tên người giao hàng không được bỏ trống',
            'ShipperName.max' => 'Tên người giao hàng không được vượt quá 50 kí tự',
            'Phone.required' => 'Số điện thoại không được bỏ trống'
        ]);

        $dataUpdate = $request->all();

        $Shipper = $this->Shipper->findOrFail($id);

        $Shipper->update($dataUpdate);

        return redirect()->route('Shipper.index')->with(['message' => 'Update  Shipper: '. $Shipper->ShipperName." success"]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $Shipper=$this->Shipper->findorfail($id);

        $Shipper->delete($Shipper);

        return redirect()->route('Shipper.index')->with(['message' => 'Delete  Shipper: '.$Shipper->ShipperName.' success']);
    }
}

resources/views/admin/Shipper/Create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="box box-primary">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{route("Shipper.store")}}" method="post">
                @csrf
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên người giao hàng:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ShipperName" name="ShipperName" value="{{old('ShipperName')}}" autofocus>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Số điện thoại:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Phone" name="Phone" value="{{old('Phone')}}">
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default bg-blue">
                            <i class="glyphicon glyphicon-floppy-disk"></i>
                            Lưu dữ liệu
                        </button>
                        <a href="{{route('Shipper.index')}}" class="btn btn-warning">quay lại</a>
                    </div>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/Shipper/Delete.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="box box-danger">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{route("Shipper.destroy",$Shipper->id)}}" method="post">
                @csrf
                @method('delete')
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên người giao hàng:</label>
                    <div class="col-sm-10">
                        <input  type="text" class="form-control" id="ShipperName" name="ShipperName" value="{{$Shipper->ShipperName}}" readonly>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Số điện thoại:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Phone" name="Phone" value="{{$Shipper->Phone}}" readonly>
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-danger ">
                            <i class="glyphicon glyphicon-trash"></i>
                            Xóa dữ liệu
                        </button>
                        <a href="{{route('Shipper.index')}}" class="btn btn-warning">quay lại</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/Shipper/Edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="box box-primary">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{route("Shipper.update",$Shipper->id)}}" method="post">
                @csrf
                @method('Put')
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên người giao hàng:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ShipperName" name="ShipperName" value="{{$Shipper->ShipperName}}" autofocus>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Số điện thoại:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Phone" name="Phone" value="{{$Shipper->Phone}}">
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default bg-blue">
                            <i class="glyphicon glyphicon-floppy-disk"></i>
                            Lưu dữ liệu
                        </button>
                        <a href="{{route('Shipper.index')}}" class="btn btn-warning">quay lại</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/Shipper/Index.blade.php
@extends('admin.layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            SHIPPER
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">SHIPPER</li>
        </ol>
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @if(session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
    </section>
    <div class=" box box-primary">
        <div class="box-body">
            <form id="formSearch" action="#" method="POST">
                @csrf
                <div class="input-group">
                    <input type="text" class="form-control list" placeholder="Search" name="searchValue" autofocus
                            value="{{ session('searchValue') }}">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            Tìm Kiếm
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                        <a href="{{route('Shipper.create')}}" class=" btn btn-primary" style="margin-left:3px">
                            <i class="glyphicon glyphicon-plus"></i>
                            Bổ sung
                        </a>
                    </div>
                </div>
            </form>
            <div id="shipperList">
            </div>
        </div>
        <script type="text/javascript">
            $(document).ready(function(){
                // Sử dụng AJAX để tìm kiếm và phân trang
                $("#formSearch").keyup(function (e) {
                    console.log('Hello World!');
                    e.preventDefault();
                    doSearch(1);
                    return;
                });
                $("#formSearch").submit(function (e) {
                    console.log('Hello World!');
                    e.preventDefault();
                    doSearch(1);
                    return;
                });
                doSearch({{$Shipper->currentPage()}});
                // Hàm thực hiện tìm kiếm và phân trang bằng AJAX
                function doSearch(page) {
                    var url = "{{route('Shipper.search')}}";
                    var postData = $("#formSearch").serializeArray();
                    postData.push({ "name": "page", "value": page });
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: postData,
                        dataType: "html",
                        error: function () {
                            alert("Your request is not valid!");
                        },
                        success: function (data) {
                            $("#shipperList").html(data);
                            $(".page-link").click(function(e) {
                                e.preventDefault();
                                var page = $(this).attr('href').split('page=')[1];
                                doSearch(page);
                            });
                        }
                    });
                }
            });
        </script>
    </div>
    @endsection

resources/views/admin/Shipper/Search.blade.php
@if($Shipper->total()>0)
    <p>Có <strong>{{$Shipper->total()}}</strong> nhà cung cấp trong tổng số <strong>{{$Shipper->lastPage()}}</strong> trang. </p>

    <table class="table table-hover table-bordered ">
        <thead class="bg-blue-gradient ">
        <th>STT</th>
        <th>Tên Nguười giao hàng</th>
        <th>Số điện thoại</th>
        <th></th>
        </thead>
        <tbody>
        @foreach($Shipper as $item)
            <tr>
                <td>{{ $loop->index+1 }}</td>
                <td>{{$item->ShipperName}}</td>
                <td>{{$item->Phone}}</td>
                <td >
                    <a href="{{route('Shipper.edit',$item->id)}}" class="btn btn-success btn-sm "><i class="glyphicon glyphicon-edit"></i> </a>
                    <a href="{{route('Shipper.show',$item->id)}}" class="btn btn-danger btn-sm "><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <!-- phân trang -->
    <div class="text-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    @if ($Shipper->currentPage() > 1)
                        <a href="{{ $Shipper->previousPageUrl() }}" class="page-link">&laquo; Previous</a>
                    @endif

                    @for ($i = 1; $i <= $Shipper->lastPage(); $i++)
                        <a href="{{ $Shipper->url($i) }}" class="page-link">{{ $i }}</a>
                    @endfor

                    @if ($Shipper->currentPage() < $Shipper->lastPage())
                        <a href="{{ $Shipper->nextPageUrl() }}" class="page-link">Next &raquo;</a>
                    @endif
                </li>
            </ul>
        </nav>
    </div>
@else
    <h2>Không tìm thấy dữ liệu muốn tìm</h2>
@endif