routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Products;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'checkUsertype'])->name('home');

Route::get('/admin/dashboard', function () {
    return view('admin.DashBoard.index');
})->middleware('auth')->name('admin.dashboard');
Route::get('/client/dashboard', function () {
    $categories=\App\Models\categories::all();
    $products=Products::paginate(10);
    return view('client.DashBoard.index',compact('products','categories'));
})->middleware('auth')->name('client.dashboard');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('Category',controller: \App\Http\Controllers\Category\CategoryController::class);
Route::get('/category', '\App\Http\Controllers\Category\CategoryController@index');

Route::get('/category/search', '\App\Http\Controllers\Category\CategoryController@search')->name('category.search');

Route::resource('Supplier',controller: \App\Http\Controllers\Supplier\SupplierController::class);
Route::resource('Product',controller: \App\Http\Controllers\Product\ProductController::class);
Route::get('/supplier/search', '\App\Http\Controllers\Supplier\SupplierController@search')->name('Supplier.search');
Route::get('/product/search', '\App\Http\Controllers\Product\ProductController@search')->name('Product.search');
Route::resource('Shipper',\App\Http\Controllers\Shipper\ShipperController::class);
Route::POST('/shipper/search', '\App\Http\Controllers\Shipper\ShipperController@search')->name('Shipper.search');
Route::resource('Customer',controller: \App\Http\Controllers\Customer\CustomerController::class);
Route::resource('Employee',controller: \App\Http\Controllers\Employee\EmployeeController::class);
Route::POST('/customer/search', '\App\Http\Controllers\Customer\CustomerController@search')->name('Customer.search');
Route::POST('/employee/search', '\App\Http\Controllers\Employee\EmployeeController@search')->name('Employee.search');
Route::resource('Order',\App\Http\Controllers\Order\OrderController::class);
Route::POST('/Order/search', '\App\Http\Controllers\Order\OrderController@search')->name('Order.search');
Route::POST('/Order/searchproduct', [\App\Http\Controllers\Order\OrderController::class, 'searchproduct'])->name('Order.searchproduct');
Route::POST('/Order/AddToCart', [\App\Http\Controllers\Order\OrderController::class, 'AddToCart'])->name('Order.AddToCart');
Route::GET('/Order/removeFromCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'removeFromCart'])->name('Order.removeFromCart');
Route::GET('/Order/RemoveCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveCart'])->name('Order.RemoveCart');
Route::POST('/Order/Init', [\App\Http\Controllers\Order\OrderController::class, 'Init'])->name('Order.Init');
Route::GET('/Order/RemoveDetail/{productId}/{orderid}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveDetail'])->name('Order.RemoveDetail');
Route::GET('/Order/Details/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Details'])->name('Order.Details');
Route::GET('/Order/Accept/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Accept'])->name('Order.Accept');
Route::GET('/Order/Shipping/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Shipping'])->name('Order.Shipping');
Route::POST('/Order/Shipped', [\App\Http\Controllers\Order\OrderController::class, 'Shipped'])->name('Order.Shipped');
Route::GET('/Order/Finished/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Finished'])->name('Order.Finished');
Route::GET('/Order/Cancel/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Cancel'])->name('Order.Cancel');
Route::GET('/Order/Reject/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Reject'])->name('Order.Reject');
Route::POST('/Client/Product/Search',[\App\Http\Controllers\client\Product\ProductController::class,'search'])->name('Client.Product.Search');
Route::GET('/Client/Product/Details/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'show'])->name('Client.Product.Details');
Route::GET('/Client/Product/AddToCart/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'AddToCart'])->name('Client.Product.AddToCart');

app/Models/Suppliers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Suppliers extends Model
{
    use HasFactory;
    protected $table='suppliers';

    protected $fillable=[
        'SupplierName',
        'ContactName',
        'Address',
        'City',
        'PostalCode',
        'Country',
        'Phone'
    ];
}

app/Http/Controllers/Supplier/SupplierController.php
<?php

namespace App\Http\Controllers\Supplier;

use App\Http\Controllers\Controller;
use App\Models\Suppliers;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    protected $Supplier;

    /**
     * @param $Supplier
     */
    public function __construct(Suppliers $Supplier)
    {
        $this->Supplier = $Supplier;
    }



    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $Supplier=$this->Supplier->latest('id')->paginate(10);

        return view('admin.Supplier.Index',compact('Supplier'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.Supplier.Create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'SupplierName' => 'required|max:50',
            'PostalCode' => 'required',
            'Address' => 'required',
            'Phone' => 'required'
        ], [
            'SupplierName.required' => 'Tên nhà cung cấp không được bỏ trống',
            'SupplierName.max' => 'Tên nhà cung cấp không được vượt quá 50 kí tự',
            'PostalCode.required' => 'Mã bưu chính không được bỏ trống',
            'Address.required' => 'Địa chỉ không được bỏ trống',
            'Phone.required' => 'Số điện thoại không được bỏ trống'
        ]);

        // Xử lý lưu dữ liệu
        $dataRequest=$request->all();

        $Supplier=$this->Supplier->create($dataRequest);


        return redirect()->route('Supplier.index')->with('success', 'Thêm mới loại hàng thành công');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $Supplier=$this->Supplier->findorfail($id);

        return view('admin.Supplier.Delete',compact('Supplier'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $Supplier=$this->Supplier->findorfail($id);
        return view('admin.Supplier.Edit',compact('Supplier'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'SupplierName' => 'required|max:50',
            'PostalCode' => 'required',
            'Address' => 'required',
            'Phone' => 'required'
        ], [
            'SupplierName.required' => 'Tên nhà cung cấp không được bỏ trống',
            'SupplierName.max' => 'Tên nhà cung cấp không được vượt quá 50 kí tự',
            'PostalCode.required' => 'Mã bưu chính không được bỏ trống',
            'Address.required' => 'Địa chỉ không được bỏ trống',
            'Phone.required' => 'Số điện thoại không được bỏ trống'
        ]);

        $dataUpdate = $request->all();

        $Supplier = $this->Supplier->findOrFail($id);

        $Supplier->update($dataUpdate);

        return redirect()->route('Supplier.index')->with(['message' => 'Update  Supplier: '. $Supplier->SupplierName." success"]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $Supplier=$this->Supplier->findorfail($id);

        $Supplier->delete($Supplier);

        return redirect()->route('Supplier.index')->with(['message' => 'Delete  Supplier: '.$Supplier->SupplierName.' success']);
    }

    /**
     *
    */
    public function search(Request $request)
    {
        $searchValue = $request->input('searchValue');

        $Supplier = $this->Supplier
            ->where('SupplierName', 'like', "%$searchValue%")
            ->orWhere('ContactName', 'like', "%$searchValue%")
            ->orWhere('Address', 'like', "%$searchValue%")
            ->orWhere('Phone', 'like', "%$searchValue%")
            ->orWhere('Country', 'like', "%$searchValue%")
            ->orWhere('City', 'like', "%$searchValue%")
            ->orWhere('PostalCode', 'like', "%$searchValue%")
            ->latest('id')
            ->paginate(10);

        return view('admin.Supplier.Index', compact('Supplier'));
    }
}

resources/views/admin/Supplier/Create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="box box-primary">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{ route('Supplier.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="hidden" class="form-control" id="SupplierID" name="SupplierID" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên nhà cung cấp:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="SupplierName" name="SupplierName" value="" autofocus>
                    </div>

                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" >Tên giao dịch:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ContactName" name="ContactName" value="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Địa chỉ:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Address" name="Address" value="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Số điện thoại:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Phone" name="Phone" value="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Quốc gia:</label>
                    <div class="col-sm-10">
                        <select class="form-control" id=" Country" name="Country">
                            <option>--Chọn Quốc Gia--</option>
                            <option value="Viet nam" selected>Viet nam</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Thành phố:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="City" name="City" value="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Mã bưu chính:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="PostalCode" name="PostalCode" value="">
                    </div>
                </div>

                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default bg-blue">
                        <i class="glyphicon glyphicon-floppy-disk"></i>
                        Lưu dữ liệu
                    </button>
                    <a href="{{route('Supplier.index')}}" class="btn btn-warning">quay lại</a>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/Supplier/Delete.blade.php
@extends('admin.layouts.app');
@section('content')
    <div class="box box-danger">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{ route('Supplier.destroy',$Supplier->id) }}" method="post">
                @csrf
                @method('Delete')
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="hidden" class="form-control" id="SupplierID" name="SupplierID" value="{{$Supplier->id}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên nhà cung cấp:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="SupplierName" name="SupplierName" value="{{$Supplier->SupplierName}}" autofocus>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" >Tên giao dịch:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ContactName" name="ContactName" value="{{$Supplier->ContactName}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Địa chỉ:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Address" name="Address" value="{{$Supplier->Address}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Số điện thoại:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="Phone" name="Phone" value="{{$Supplier->Phone}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Quốc gia:</label>
                    <div class="col-sm-10">
                        <select class="form-control" id=" Country" name="Country">
                            <option>--Chọn Quốc Gia--</option>
                            <option value="{{$Supplier->Country}}" selected>{{$Supplier->Country}}</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Thành phố:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="City" name="City" value="{{$Supplier->City}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Mã bưu chính:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="PostalCode" name="PostalCode" value="{{$Supplier->PostalCode}}">
                    </div>
                </div>

                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-danger ">
                        <i class="glyphicon glyphicon-trash"></i>
                        Xóa dữ liệu
                    </button>
                    <a href="{{route('Supplier.index')}}" class="btn btn-warning">quay lại</a>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/Supplier/Edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="box box-primary">
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form class="form-horizontal" action="{{ route('Supplier.update',$Supplier->id) }}" method="post">
                @csrf
                @method('PUT')
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input type="hidden" class="form-control" id="SupplierID" name="SupplierID" value="{{$Supplier->id}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2">Tên nhà cung cấp:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="SupplierName" name="SupplierName" value="{{$Supplier->SupplierName}}" autofocus>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" >Tên giao dịch:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="ContactName" name="ContactName" value="{{$Supplier->ContactName}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Địa chỉ:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="Address" name="Address" value="{{$Supplier->Address}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Số điện thoại:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="Phone" name="Phone" value="{{$Supplier->Phone}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Quốc gia:</label>
                            <div class="col-sm-10">
                                <select class="form-control" id=" Country" name="Country">
                                    <option>--Chọn Quốc Gia--</option>
                                    <option value="{{$Supplier->Country}}" selected>{{$Supplier->Country}}</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Thành phố:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="City" name="City" value="{{$Supplier->City}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Mã bưu chính:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="PostalCode" name="PostalCode" value="{{$Supplier->PostalCode}}">
                            </div>
                        </div>

                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default bg-blue">
                            <i class="glyphicon glyphicon-floppy-disk"></i>
                            Lưu dữ liệu
                        </button>
                        <a href="{{route('Supplier.index')}}" class="btn btn-warning">quay lại</a>
                    </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/Supplier/Index.blade.php
@extends('admin.layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            SUPPLIER
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">SUPPLIER</li>
        </ol>
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @if(session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
    </section>

    <!-- Main content -->
    <section class="content">
        <div class=" box box-primary">
            <div class="box-body">
                <form id="formSearch" action="{{ route('Supplier.search') }}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="searchValue" autofocus
                               value="{{old('searchValue')}}">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                Tìm Kiếm
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                            <a href="{{route('Supplier.create')}}" class=" btn btn-primary" style="margin-left:3px">
                                <i class="glyphicon glyphicon-plus"></i>
                                Bổ sung
                            </a>
                        </div>
                    </div>
                </form>
                <div>
                    <p>Có <strong> {{$Supplier->total()}} </strong> kết quả trong tổng số
                        <strong>{{ $Supplier->lastPage() }}</strong> trang.
                    </p>
                    <table class="table table-hover table-bordered ">
                        <thead class="bg-blue-gradient ">
                            <th>STT</th>
                            <th>Tên nhà cung cấp</th>
                            <th>Tên giao dịch</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Quốc gia</th>
                            <th>Thành phố </th>
                            <th>Mã bưu chính</th>
                            <th style="width:100px"></th>
                        </thead>
                        <tbody>

                        @foreach ($Supplier as $items)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{$items->SupplierName}}</td>
                                <td>{{$items->ContactName}}</td>
                                <td>{{$items->Address}}</td>
                                <td>{{$items->Phone}}</td>
                                <td>{{$items->Country}}</td>
                                <td>{{$items->City}}</td>
                                <td>{{$items->PostalCode}}</td>
                                <td>
                                    <a href="{{ route('Supplier.edit',$items->id)}}" class="btn btn-success btn-sm sm"><i  class="glyphicon glyphicon-edit"></i></a>
                                    <a href="{{ route('Supplier.show',$items->id)}}" class="btn btn-danger btn-sm sm"><i
                                            class="glyphicon glyphicon-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    <div class="text-center">
                        <nav aria-label="Page navigation example">

                        </nav>
                    </div>
                </div>


            </div>
        </div>

    </section>
    <!-- /.content -->

    <!-- phân trang -->
    <div class="text-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    @if ($Supplier->currentPage() > 1)
                        <a href="{{ $Supplier->previousPageUrl() }}" class="page-link">&laquo; Previous</a>
                    @endif

                    @for ($i = 1; $i <= $Supplier->lastPage(); $i++)
                        <a href="{{ $Supplier->url($i) }}" class="page-link">{{ $i }}</a>
                    @endfor

                    @if ($Supplier->currentPage() < $Supplier->lastPage())
                        <a href="{{ $Supplier->nextPageUrl() }}" class="page-link">Next &raquo;</a>
                    @endif
                </li>
            </ul>
        </nav>
    </div>

@endsection