routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Products;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'checkUsertype'])->name('home');

Route::get('/admin/dashboard', function () {
    return view('admin.DashBoard.index');
})->middleware('auth')->name('admin.dashboard');
Route::get('/client/dashboard', function () {
    $categories=\App\Models\categories::all();
    $products=Products::paginate(10);
    return view('client.DashBoard.index',compact('products','categories'));
})->middleware('auth')->name('client.dashboard');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('Category',controller: \App\Http\Controllers\Category\CategoryController::class);
Route::get('/category', '\App\Http\Controllers\Category\CategoryController@index');

Route::get('/category/search', '\App\Http\Controllers\Category\CategoryController@search')->name('category.search');

Route::resource('Supplier',controller: \App\Http\Controllers\Supplier\SupplierController::class);
Route::resource('Product',controller: \App\Http\Controllers\Product\ProductController::class);
Route::get('/supplier/search', '\App\Http\Controllers\Supplier\SupplierController@search')->name('Supplier.search');
Route::get('/product/search', '\App\Http\Controllers\Product\ProductController@search')->name('Product.search');
Route::resource('Shipper',\App\Http\Controllers\Shipper\ShipperController::class);
Route::POST('/shipper/search', '\App\Http\Controllers\Shipper\ShipperController@search')->name('Shipper.search');
Route::resource('Customer',controller: \App\Http\Controllers\Customer\CustomerController::class);
Route::resource('Employee',controller: \App\Http\Controllers\Employee\EmployeeController::class);
Route::POST('/customer/search', '\App\Http\Controllers\Customer\CustomerController@search')->name('Customer.search');
Route::POST('/employee/search', '\App\Http\Controllers\Employee\EmployeeController@search')->name('Employee.search');
Route::resource('Order',\App\Http\Controllers\Order\OrderController::class);
Route::POST('/Order/search', '\App\Http\Controllers\Order\OrderController@search')->name('Order.search');
Route::POST('/Order/searchproduct', [\App\Http\Controllers\Order\OrderController::class, 'searchproduct'])->name('Order.searchproduct');
Route::POST('/Order/AddToCart', [\App\Http\Controllers\Order\OrderController::class, 'AddToCart'])->name('Order.AddToCart');
Route::GET('/Order/removeFromCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'removeFromCart'])->name('Order.removeFromCart');
Route::GET('/Order/RemoveCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveCart'])->name('Order.RemoveCart');
Route::POST('/Order/Init', [\App\Http\Controllers\Order\OrderController::class, 'Init'])->name('Order.Init');
Route::GET('/Order/RemoveDetail/{productId}/{orderid}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveDetail'])->name('Order.RemoveDetail');
Route::GET('/Order/Details/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Details'])->name('Order.Details');
Route::GET('/Order/Accept/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Accept'])->name('Order.Accept');
Route::GET('/Order/Shipping/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Shipping'])->name('Order.Shipping');
Route::POST('/Order/Shipped', [\App\Http\Controllers\Order\OrderController::class, 'Shipped'])->name('Order.Shipped');
Route::GET('/Order/Finished/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Finished'])->name('Order.Finished');
Route::GET('/Order/Cancel/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Cancel'])->name('Order.Cancel');
Route::GET('/Order/Reject/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Reject'])->name('Order.Reject');
Route::POST('/Client/Product/Search',[\App\Http\Controllers\client\Product\ProductController::class,'search'])->name('Client.Product.Search');
Route::GET('/Client/Product/Details/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'show'])->name('Client.Product.Details');
Route::GET('/Client/Product/AddToCart/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'AddToCart'])->name('Client.Product.AddToCart');

resources/views/admin/layouts/ControlSideBar.blade.php
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>

resources/views/admin/layouts/_Footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

resources/views/admin/layouts/_Header.blade.php
<header class="main-header">
    <!-- Biểu tượng -->
    <a href="/admin/dashboard" class="logo">
        <!-- biểu trưng nhỏ cho thanh bên nhỏ 50x50 pixel -->
        <span class="logo-mini">Mini</span>
        <!-- biểu trưng cho trạng thái thông thường và thiết bị di động -->
        <span class="logo-lg"><b>Trung Shop</b></span>
    </a>
    <!-- Header Navbar: kiểu có thể được tìm thấy trong header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Nút chuyển đổi thanh bên-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Chuyển đổi điều hướng</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Tài khoản người dùng: kiểu có thể được tìm thấy trong dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{asset('Images/canhan.png')}}" class="user-image" alt="">
                        <span class="hidden-xs"> {{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- Hình ảnh người dùng -->
                        <li class="user-header">
                            <img src="{{asset('Images/canhan.png')}}" class="img-circle" alt="">
                            <p>
                                 {{ Auth::user()->name }}

                                <small>{{Auth::user()->email }}</small>
                            </p>
                        </li>
                        <!--Chân trang trình đơn-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Thông Tin</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" class="btn btn-default btn-flat"  onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Thoát') }}
                                </a>
                            </div>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/_Sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="treeview">
                <a href="/">
                    <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
                </a>

            </li>
            <li class="treeview active">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Quản lý dữ liệu</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('Category.index')}}"><i class="fa fa-circle-o"></i> Loại hàng</a></li>
                    <li><a href="{{route('Product.index')}}"><i class="fa fa-circle-o"></i> Mặt hàng</a></li>
                    <li><a href="{{route('Supplier.index')}}"><i class="fa fa-circle-o"></i> Nhà cung cấp</a></li>
                    <li><a href="{{route('Customer.index')}}"><i class="fa fa-circle-o"></i> Khách hàng</a></li>
                    <li><a href="{{route('Shipper.index')}}"><i class="fa fa-circle-o"></i> Giao hàng</a></li>
                    <li><a href="{{route('Employee.index')}}"><i class="fa fa-circle-o"></i> Nhân viên</a></li>
                </ul>
            </li>
            <li class="treeview active">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Bán hàng</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('Order.create')}}"><i class="fa fa-circle-o"></i> Lập đơn hàng</a></li>
                    <li><a href="{{route('Order.index')}}"><i class="fa fa-circle-o"></i> Tra cứu đơn hàng</a></li>
                </ul>
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/Ionicons/css/ionicons.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('admin/Themes/dist/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('admin/Themes/dist/css/skins/_all-skins.min.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/morris.js/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/jvectormap/jquery-jvectormap.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('admin/Themes/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('admin/Themes/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <script src="{{asset('admin/Themes/bower_components/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{asset('admin/Themes/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <!-- SlimScroll -->
    <script src="{{asset('admin/Themes/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('admin/Themes/bower_components/fastclick/lib/fastclick.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('admin/Themes/dist/js/adminlte.min.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{asset('admin/Themes/dist/js/demo.js')}}"></script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    @include('admin.layouts._Header')
    <!-- Left side column. contains the logo and sidebar -->
    @include('admin.layouts._Sidebar')
    <div class="content-wrapper">
    <!-- Content Wrapper. Contains page content -->
    @yield('content')
    </div>
    <!-- /.content-wrapper -->
    @include('admin.layouts._Footer');

    <!-- Control Sidebar -->
{{--    @include('admin.layouts.ControlSideBar')--}}
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->


</body>
</html>