routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Products;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'checkUsertype'])->name('home');

Route::get('/admin/dashboard', function () {
    return view('admin.DashBoard.index');
})->middleware('auth')->name('admin.dashboard');
Route::get('/client/dashboard', function () {
    $categories=\App\Models\categories::all();
    $products=Products::paginate(10);
    return view('client.DashBoard.index',compact('products','categories'));
})->middleware('auth')->name('client.dashboard');



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('Category',controller: \App\Http\Controllers\Category\CategoryController::class);
Route::get('/category', '\App\Http\Controllers\Category\CategoryController@index');

Route::get('/category/search', '\App\Http\Controllers\Category\CategoryController@search')->name('category.search');

Route::resource('Supplier',controller: \App\Http\Controllers\Supplier\SupplierController::class);
Route::resource('Product',controller: \App\Http\Controllers\Product\ProductController::class);
Route::get('/supplier/search', '\App\Http\Controllers\Supplier\SupplierController@search')->name('Supplier.search');
Route::get('/product/search', '\App\Http\Controllers\Product\ProductController@search')->name('Product.search');
Route::resource('Shipper',\App\Http\Controllers\Shipper\ShipperController::class);
Route::POST('/shipper/search', '\App\Http\Controllers\Shipper\ShipperController@search')->name('Shipper.search');
Route::resource('Customer',controller: \App\Http\Controllers\Customer\CustomerController::class);
Route::resource('Employee',controller: \App\Http\Controllers\Employee\EmployeeController::class);
Route::POST('/customer/search', '\App\Http\Controllers\Customer\CustomerController@search')->name('Customer.search');
Route::POST('/employee/search', '\App\Http\Controllers\Employee\EmployeeController@search')->name('Employee.search');
Route::resource('Order',\App\Http\Controllers\Order\OrderController::class);
Route::POST('/Order/search', '\App\Http\Controllers\Order\OrderController@search')->name('Order.search');
Route::POST('/Order/searchproduct', [\App\Http\Controllers\Order\OrderController::class, 'searchproduct'])->name('Order.searchproduct');
Route::POST('/Order/AddToCart', [\App\Http\Controllers\Order\OrderController::class, 'AddToCart'])->name('Order.AddToCart');
Route::GET('/Order/removeFromCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'removeFromCart'])->name('Order.removeFromCart');
Route::GET('/Order/RemoveCart/{productId}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveCart'])->name('Order.RemoveCart');
Route::POST('/Order/Init', [\App\Http\Controllers\Order\OrderController::class, 'Init'])->name('Order.Init');
Route::GET('/Order/RemoveDetail/{productId}/{orderid}', [\App\Http\Controllers\Order\OrderController::class, 'RemoveDetail'])->name('Order.RemoveDetail');
Route::GET('/Order/Details/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Details'])->name('Order.Details');
Route::GET('/Order/Accept/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Accept'])->name('Order.Accept');
Route::GET('/Order/Shipping/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Shipping'])->name('Order.Shipping');
Route::POST('/Order/Shipped', [\App\Http\Controllers\Order\OrderController::class, 'Shipped'])->name('Order.Shipped');
Route::GET('/Order/Finished/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Finished'])->name('Order.Finished');
Route::GET('/Order/Cancel/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Cancel'])->name('Order.Cancel');
Route::GET('/Order/Reject/{OrderId}', [\App\Http\Controllers\Order\OrderController::class, 'Reject'])->name('Order.Reject');
Route::POST('/Client/Product/Search',[\App\Http\Controllers\client\Product\ProductController::class,'search'])->name('Client.Product.Search');
Route::GET('/Client/Product/Details/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'show'])->name('Client.Product.Details');
Route::GET('/Client/Product/AddToCart/{ProductID}', [\App\Http\Controllers\client\Product\ProductController::class, 'AddToCart'])->name('Client.Product.AddToCart');

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Resources\CategoryResource;
use App\Models\categories;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    protected $category;

    /**
     * @param $category
     */
    public function __construct(categories $category)
    {
        $this->category = $category;
    }


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $category=$this->category->paginate(10);

        $categoryResource=CategoryResource::collection($category)->response()->getData(true);


        return response()->json(['data'=>$categoryResource],Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        //lấy dữ liệu về từ resquest
        $DataRequest=$request->all();

        $Category=$this->category->create($DataRequest);

        $categoryResource=  new CategoryResource($Category);

        return response()->json(['data'=>$categoryResource],Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $Category=$this->category->findorfail($id);

        $CategoryResource= new CategoryResource($Category);

        return response()->json(['data'=>$CategoryResource],Response::HTTP_OK);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //lấy dữ liệu về từ resquest
        $DataRequest=$request->all();

        $Category=$this->category->findorfail($id);

        $Category->update($DataRequest);

        $CategoryResource= new CategoryResource($Category);

        return response()->json(['data'=>$CategoryResource],Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data =$this->category->findorfail($id);
        if ($data) {
            $data->delete();
            return response()->json(['message' => 'Xóa thành công'], Response::HTTP_OK);
        } else {
            return response()->json(['message' => 'Không tìm thấy dữ liệu'],Response::HTTP_NOT_FOUND);
        }
    }
}

app/Http/Controllers/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Category;

use App\Http\Controllers\Controller;
use App\Models\categories;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $category;

    /**
     * @param $category
     */
    public function __construct(categories $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = $this->category->latest('id')->paginate(10);

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.categories.Create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'CategoryName' => 'required|max:50',
            'Description' => 'required',
            'ParentCategoryID' => 'nullable|numeric'
        ], [
            'CategoryName.required' => 'Tên loại hàng không được bỏ trống',
            'CategoryName.max' => 'Tên loại hàng không được vượt quá 50 kí tự',
            'Description.required' => 'Mô tả không được bỏ trống',
            'ParentCategoryID.numeric' => 'Mã loại hàng gốc phải là số'
        ]);

        // Xử lý lưu dữ liệu
        $dataRequest=$request->all();

        $Category=$this->category->create($dataRequest);


        return redirect()->route('Category.index')->with('success', 'Thêm mới loại hàng thành công');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $Category=$this->category->findorfail($id);

        return view('admin.categories.Delete',compact('Category'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($categoriesID)
    {

        $Category=$this->category->findorfail($categoriesID);
        return view('admin.categories.Edit',compact('Category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            'CategoryName' => 'required|max:50',
            'Description' => 'required',
            'ParentCategoryID' => 'nullable|numeric'
        ], [
            'CategoryName.required' => 'Tên loại hàng không được bỏ trống',
            'CategoryName.max' => 'Tên loại hàng không được vượt quá 50 kí tự',
            'Description.required' => 'Mô tả không được bỏ trống',
            'ParentCategoryID.numeric' => 'Mã loại hàng gốc phải là số'
        ]);

        $dataUpdate = $request->all();

        $category = $this->category->findOrFail($id);

        $category->update($dataUpdate);

        return redirect()->route('Category.index')->with(['message' => 'Update  category: '. $category->CategoryName." success"]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $Category=$this->category->findorfail($id);

        $Category->delete($Category);

        return redirect()->route('Category.index')->with(['message' => 'Delete  category: '.$Category->CategoryName.' success']);
    }
    /**
     * Tìm kiếm theo Key
    */
    public function search(Request $request)
    {
        $searchValue = $request->input('searchValue');

        $categories = $this->category
            ->where('CategoryName', 'like', "%$searchValue%")
            ->orWhere('Description', 'like', "%$searchValue%")
            ->latest('id')
            ->paginate(10);

        return view('admin.categories.index', compact('categories'));
    }
}

resources/views/admin/categories/Create.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="box box-primary">
    <div class="box-body">
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form class="form-horizontal" action="{{ route('Category.store') }}" method="post">
            @csrf
            <div class="form-group">
                <label class="control-label col-sm-2">Tên loại hàng:</label>
                <div class="col-sm-10">
                    <input class="form-control" autofocus name="CategoryName"  required>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Mô tả:</label>
                <div class="col-sm-10">
                    <input class="form-control"  name="Description" ">
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Mã loại hàng gốc:</label>
                <div class="col-sm-10">
                    <input class="form-control"  name="ParentCategoryID" " required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default bg-blue">
                        <i class="glyphicon glyphicon-floppy-disk"></i>
                        Lưu dữ liệu
                    </button>
                    <a href="/Category" class="btn btn-warning">quay lại</a>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/Delete.blade.php
@extends('admin.layouts.app');
@section('content')
    <div class="box box-danger">
        <div class="box-body">
            <form class="form-horizontal" action="{{ route('Category.destroy',$Category->id) }}" method="post">
                @csrf
                @method('delete')
                <div class="form-group">
                    <label class="control-label col-sm-2">Tên loại hàng:</label>
                    <div class="col-sm-10">
                        <input class="form-control" autofocus name="CategoryName" value="{{optional($Category)->CategoryName}}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Mô tả:</label>
                    <div class="col-sm-10">
                        <input class="form-control"  name="Description" value="{{optional($Category)->Description}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Mã loại hàng gốc:</label>
                    <div class="col-sm-10">
                        <input class="form-control"  name="ParentCategoryID" value="{{optional($Category)->ParentCategoryID}}" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-danger ">
                            <i class="glyphicon glyphicon-trash"></i>
                            Xóa dữ liệu
                        </button>
                        <a href="/Category" class="btn btn-warning">quay lại</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/Edit.blade.php
@extends('admin.layouts.app');
@section('content')
<div class="box box-primary">
    <div class="box-body">
        @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form class="form-horizontal" action="{{ route('Category.update',$Category->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label class="control-label col-sm-2">Tên loại hàng:</label>
                <div class="col-sm-10">
                    <input class="form-control" autofocus name="CategoryName" value="{{optional($Category)->CategoryName}}" required>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Mô tả:</label>
                <div class="col-sm-10">
                    <input class="form-control"  name="Description" value="{{optional($Category)->Description}}">
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2">Mã loại hàng gốc:</label>
                <div class="col-sm-10">
                    <input class="form-control"  name="ParentCategoryID" value="{{optional($Category)->ParentCategoryID}}" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default bg-blue">
                        <i class="glyphicon glyphicon-floppy-disk"></i>
                        Lưu dữ liệu
                    </button>
                    <a href="/Category" class="btn btn-warning">quay lại</a>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            CATEGORY
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">CATEGORY</li>
        </ol>
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @if(session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
    </section>

    <!-- Main content -->
    <section class="content">
        <div class=" box box-primary">
            <div class="box-body">
                <form id="formSearch" action="{{ route('category.search') }}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="searchValue" autofocus
                               value="{{old('searchValue')}}">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                Tìm Kiếm
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                            <a href="{{route('Category.create')}}" class=" btn btn-primary" style="margin-left:3px">
                                <i class="glyphicon glyphicon-plus"></i>
                                Bổ sung
                            </a>
                        </div>
                    </div>
                </form>
                <div>
                    <p>Có <strong> {{$categories->total()}} </strong> kết quả trong tổng số
                        <strong>{{ $categories->lastPage() }}</strong> trang.
                    </p>
                    <table class="table table-hover table-bordered ">
                        <thead class="bg-blue-gradient ">
                        <th style="width:10px">STT</th>
                        <th>Tên loại hàng</th>
                        <th>Mô tả</th>
                        <th>Mã danh mục gốc</th>
                        <th style="width:130px">Số sản phẩm</th>
                        <th style="width:100px"></th>
                        </thead>
                        <tbody>

                        @foreach ($categories as $items)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{$items->CategoryName}}</td>
                                <td>{{$items->Description}}</td>
                                <td>{{$items->ParentCategoryID}}</td>
                                <td>{{\App\Models\Products::where('categories_id', $items->id)->count()}}</td>
                                <td>
                                    <a href="{{ route('Category.edit',$items->id)}}" class="btn btn-success btn-sm sm"><i  class="glyphicon glyphicon-edit"></i></a>
                                    <a href="{{ route('Category.show',$items->id)}}" class="btn btn-danger btn-sm sm"><i
                                            class="glyphicon glyphicon-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    <div class="text-center">
                        <nav aria-label="Page navigation example">

                        </nav>
                    </div>
                </div>


            </div>
        </div>

    </section>
    <!-- /.content -->

    <!-- phân trang -->
    <div class="text-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
        @if ($categories->currentPage() > 1)
            <a href="{{ $categories->previousPageUrl() }}" class="page-link">&laquo; Previous</a>
        @endif

        @for ($i = 1; $i <= $categories->lastPage(); $i++)
            <a href="{{ $categories->url($i) }}" class="page-link">{{ $i }}</a>
        @endfor

        @if ($categories->currentPage() < $categories->lastPage())
            <a href="{{ $categories->nextPageUrl() }}" class="page-link">Next &raquo;</a>
        @endif
                </li>
            </ul>
        </nav>
    </div>

@endsection